### ISSUE TITLE
Split Introduction to Programming in Python into a collection of chapters

### ISSUE THREAD

**Issue by mateuszwyszynski** [lazarskiopencourses/lazarskiopencourses.github.io#11]

**Comment by wisniewski-mateusz** [comment]
Czy Wprowadzenie do programowania też rozbijać na collections?
@mateuszwyszynski

**Comment by mateuszwyszynski** [comment]
Tak

**Comment by wisniewski-mateusz** [comment]
@mateuszwyszynski zrobione. Sprawdź, czy nie zmienić opisów pod modułami, bo już za długo przy tych rzeczach siedzę i nie wiem czy nie są cringowe xd
